// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucshyazqtcssznvqzgrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjc2h5YXpxdGNzc3pudnF6Z3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDc1NjYsImV4cCI6MjA2MDUyMzU2Nn0.h54xJkWJkpr4_Q_1iamv-g9iUMt0QSwlmEXAg95Bl5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);